// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcceptResponse = { blank_id: string, accept: Array<string>, 
/**
 * The verdict the answer gets now, which should be correct.
 */
verdict: unknown, };
