// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rating } from "./Rating";

export type CheckResponse = { graded: unknown, rating: Rating, interval_days: number, due: string, };
