// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rating } from "./Rating";

export type CheckRequest = { 
/**
 * Blank id to what the user typed.
 */
answers: { [key in string]: string }, 
/**
 * Overrides the rating computed from the score.
 */
rating_override: Rating | null, };
