// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientItem } from "./ClientItem";
import type { Level } from "./Level";

/**
 * A sheet as the browser sees it: the same sentences with the answers removed.
 */
export type ClientSheet = { sheet_id: number, topic_id: string, topic_title: string, topic_category: string, cefr: Level, items: Array<ClientItem>, };
