// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientSegment } from "./ClientSegment";

export type ClientItem = { n: number, segments: Array<ClientSegment>, hint: string | null, };
