// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One column of a chart: a date and what happened on it.
 */
export type DayPoint = { date: string, count: number, 
/**
 * Share of blanks correct that day, absent when nothing was studied.
 */
accuracy: number | null, };
