// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rating } from "./Rating";

export type FinishResponse = { topic_title: string, rating: Rating, interval_days: number, due: string, correct: number, total: number, accuracy: number, 
/**
 * Topics still due after this one.
 */
remaining: number, };
