// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rating } from "./Rating";

export type ItemVerdict = { correct: boolean, 
/**
 * What this single item earned, before the run is averaged.
 */
grade: Rating, results: unknown, };
