// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One item as the browser reports it.
 */
export type ItemAnswer = { n: number, 
/**
 * Milliseconds from the sentence appearing to the answer being sent.
 */
elapsed_ms: number, 
/**
 * Blank id to what was typed.
 */
answers: { [key in string]: string }, };
