// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";

export type LevelProgress = { level: Level, total: number, studied: number, due: number, };
