// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CEFR level, as labelled by the source curriculum.
 */
export type Level = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
