// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How well a whole sheet went. Maps one to one onto the FSRS buttons.
 */
export type Rating = "again" | "hard" | "good" | "easy";
