// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientSheet } from "./ClientSheet";

/**
 * The next thing to study, or nothing when the queue is empty.
 */
export type ReviewQueue = { sheet: ClientSheet | null, 
/**
 * Topics still due after this one.
 */
remaining: number, };
