// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayPoint } from "./DayPoint";
import type { LevelProgress } from "./LevelProgress";
import type { TopicScore } from "./TopicScore";
import type { Weakness } from "./Weakness";

export type Stats = { today: string, topics_total: number, topics_studied: number, topics_due: number, reviews_total: number, blanks_total: number, blanks_correct: number, 
/**
 * 0.0 to 1.0 across every blank ever answered.
 */
accuracy: number, streak_days: number, by_level: Array<LevelProgress>, 
/**
 * One entry per day for the last 30 days, including empty ones.
 */
activity: Array<DayPoint>, 
/**
 * One entry per day for the next 14 days, including empty ones.
 */
forecast: Array<DayPoint>, weakest: Array<Weakness>, hardest: Array<TopicScore>, };
