// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";

export type TopicView = { id: string, cefr: Level, stage: number, category: string, title: string, goal: string, 
/**
 * `null` until the topic has been studied once.
 */
due: string | null, reps: number, lapses: number, is_due: boolean, is_new: boolean, 
/**
 * True when a sheet for this topic already exists on disk or in the database.
 */
has_sheet: boolean, };
