// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";

export type TopicScore = { id: string, title: string, cefr: Level, accuracy: number, reviews: number, lapses: number, };
